Error loading items for a category
Error: sqlalchemy.exc.ProgrammingError 

Replication Steps:
1) $ python db_setup.py
2) $ python db_populate.py
3) launch project.py in debug mode
4) http://localhost:8000/login
5) Google Sign-In & select your Google profile (FB not setup yet)
6) select a Category
Expected Result: - Items for that Category are listed
Actual Result: - sqlalchemy.exc.ProgrammingError
sqlalchemy.exc.ProgrammingError
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18968 and this is thread id 11224. [SQL: 'SELECT item.title AS item_title, item.id AS item_id, item.description AS item_description, item.fk_cat_name AS item_fk_cat_name, item.date_added AS item_date_added \nFROM item \nWHERE item.fk_cat_name = ?'] [parameters: [{}]] (Background on this error at: http://sqlalche.me/e/f405)

Traceback (most recent call last)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2309, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2295, in wsgi_app
response = self.handle_exception(e)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1741, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\_compat.py", line 35, in reraise
raise value
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "c:\Users\user\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\home\dkbedi\fullstack-nanodegree-vm\vagrant\catalog\project.py", line 151, in showItems
items = session.query(Item).filter_by(fk_cat_name=category_name).all()
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 2843, in all
return list(self)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 2995, in __iter__
return self._execute_and_instances(context)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\query.py", line 3018, in _execute_and_instances
result = conn.execute(querycontext.statement, self._params)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
return meth(self, multiparams, params)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
return connection._execute_clauseelement(self, multiparams, params)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
compiled_sql, distilled_params
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1132, in _execute_context
None, None)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
exc_info
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
raise value.with_traceback(tb)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1127, in _execute_context
context = constructor(dialect, self, conn, *args)
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 639, in _init_compiled
self.cursor = self.create_cursor()
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 954, in create_cursor
return self._dbapi_connection.cursor()
File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\pool.py", line 977, in cursor
return self.connection.cursor(*args, **kwargs)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 18968 and this is thread id 11224. [SQL: 'SELECT item.title AS item_title, item.id AS item_id, item.description AS item_description, item.fk_cat_name AS item_fk_cat_name, item.date_added AS item_date_added \nFROM item \nWHERE item.fk_cat_name = ?'] [parameters: [{}]] (Background on this error at: http://sqlalche.me/e/f405)
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object